--Creacion de la tabla zapatos
CREATE TABLE ZAPATOS (
   id_zapato NUMBER(11) ,
   tipo_zapato VARCHAR2(20),
   marca_zapato VARCHAR2(20),
   min_stock  NUMBER(5)
   
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";

