--Creacion de la tabla zapatos
CREATE TABLE ZAPATOS (
   id NUMBER(11) ,
   marca VARCHAR2(20),
   modelo VARCHAR2(20),
   tipo  NUMBER(5),
   material VARCHAR2(20),
   material_suela VARCHAR2(20),
   estado VARCHAR2(10)
   
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";


--Creacion de la tabla zap_tall_col
CREATE TABLE DETALLES (
   id_zap_tall_col NUMBER(11) ,
   id_factura NUMBER(11),
   descuento  NUMBER(5,2)   
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";



--Creacion de la tabla de auditoria
CREATE TABLE CONTROL_LOG (
   COD_EMPLEADO NUMBER,
   FECHA DATE,
   TABLA VARCHAR2(20 BYTE),
   COD_OPERACION CHAR(1 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";
REM INSERTING into HR.LINEAS_FACTURA
SET DEFINE OFF;

--Creacion de la tabla usuarios
CREATE TABLE USUARIOS_ZAPATERIA (
   usuario  VARCHAR2(30),
   contrasenia  VARCHAR2(20),
   rol       VARCHAR2(10)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";