DROP TABLE ZAPATOS;
DROP TABLE ZAP_TALL_COL;
DROP TABLE DETALLES;
DROP TABLE FACTURAS;
DROP TABLE CONTROL_LOG;
DROP TABLE USUARIOS_ZAPATERIA;

--Creacion de la tabla zapatos
CREATE TABLE ZAPATOS (
   id_zapato NUMBER(11) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
   marca VARCHAR2(20),
   modelo VARCHAR2(20),
   tipo  VARCHAR2(32),
   material VARCHAR2(20),
   material_suela VARCHAR2(20),
   estado VARCHAR2(10)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";


--Creacion de la tabla zap_tall_col
CREATE TABLE ZAP_TALL_COL (
   id_zap_tall_col NUMBER(11) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
   id_zapato NUMBER(11) ,
   talla NUMBER(3,1),
   color  VARCHAR2(20),  
   stock  NUMBER(10),
   min_stock NUMBER(5),
   precio NUMBER(11)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";


--Creacion de la tabla detalles
CREATE TABLE DETALLES (
   id_zap_tall_col NUMBER(11),
   id_factura NUMBER(11),
   unidades   NUMBER(5),
   descuento  NUMBER(5,2)   
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";

--Creacion de la tabla facturas
CREATE TABLE FACTURAS (
   id_factura NUMBER(11) GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
   nombre_cliente VARCHAR2(128),
   total NUMBER(11,2),
   fecha_venta DATE,
   usuario VARCHAR2(30)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";

--Creacion de la tabla de auditoria
CREATE TABLE CONTROL_LOG (
   COD_EMPLEADO VARCHAR(32),
   FECHA DATE,
   TABLA VARCHAR2(20 BYTE),
   COD_OPERACION CHAR(1 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";

--Creacion de la tabla usuarios
CREATE TABLE USUARIOS_ZAPATERIA (
   usuario  VARCHAR2(30),
   contrasenia  VARCHAR2(20),
   rol       VARCHAR2(10)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE
DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS"

